from .kth import KTHScraper
from .ntnu import NTNUScraper
from .chalmers import ChalmersScraper
from .aalborg import AalborgScraper
from .iaea import IAEAScraper
from .oecd_iea import OECDIEAScraper
from .html_scraper import GenericHtmlScraper
from .hub_scraper import GenericHubScraper
from .js_scraper import GenericJSScraper