from .kth import KTHScraper
from .ntnu import NTNUScraper
from .chalmers import ChalmersScraper
from .aalborg import AalborgScraper
from .iaea import IAEAScraper
from .oecd_iea import OECDIEAScraper
from .rmi import RMIScraper
from .careers_gov import CareersGovScraper
from .ramboll import RambollScraper
from .ait import AITScraper
from .csh import CSHScraper
from .iiasa import IIASAScraper
from .dtu_oracle import DTUOracleScraper
from .html_scraper import GenericHtmlScraper
from .hub_scraper import GenericHubScraper
from .js_scraper import GenericJSScraper
